# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.CharField(default='goo', max_length=100),
            preserve_default=False,
        ),
    ]
